apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "label-generator" . | nindent 4 }}
    module: {{ .Values.module }}
  name: {{ .Values.module }}-{{ .Values.environment }}-deployment
  namespace: {{ .Values.module }}-{{ .Values.environment }}
spec:
  progressDeadlineSeconds: 600  # 10 minutes au lieu des 10 minutes par défaut
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.module }}-{{ .Values.environment }}
  template:
    metadata:
      labels:
        app: {{ .Values.module }}-{{ .Values.environment }}
    spec:
      containers:
        - name: {{ .Values.containers.name }}
          image: {{ .Values.containers.image }}:{{ .Values.containers.tags }}
          ports:
            - containerPort: {{ .Values.containers.ports.containerPort }}
          resources:
            {{- toYaml .Values.containers.resources | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
          readinessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 60
            periodSeconds: 20
          env:
            - name: KAFKA_TOPICS
              value: ""{{ .Values.kafka.topics | join \",\" }}""
      {{- if .Values.volumes }}
      volumes:
        {{- toYaml .Values.volumes | nindent 12 }}
      {{- end }}
