{{- range $topic := .Values.topics }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ $.Release.Name }}  # {{ $.Values.cluster.name }}
  name: {{ $topic.name }}
  namespace: {{ $.Values.module }}-{{ $.Values.environment }}  # Notez le $
spec:
  config:
    retention.ms: "540000"
  partitions: {{ $topic.partitions }}
  replicas: {{ $topic.replicationFactor }}
  topicName: {{ $topic.name | replace "-" "." }}
{{- end }}