apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: {{ .Values.module }}-{{ .Values.environment }}
  labels:
    app.kubernetes.io/instance: {{ .Values.module }}-{{ .Values.environment }}
data:
  server.properties: |
{{ .Files.Get .Values.server.file | indent 4 }}