# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{-  include "label-generator" . | nindent 4 }}
    module: {{ .Values.module }}
  name: {{ .Values.module }}-{{ .Values.environment }}-deployment
  namespace: {{ .Values.module }}-{{ .Values.environment }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.module }}-{{ .Values.environment }}
  template:
    metadata:
      labels:
        app: {{ .Values.module }}-{{ .Values.environment }}
    spec:
      containers:
        - name: {{ .Values.containers.name }}
          image: {{ .Values.containers.image }}:{{ .Values.containers.tags }}
          ports:
            - containerPort: {{ .Values.containers.ports.containerPort }}
          resources:
            {{- toYaml .Values.containers.resources | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}