apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-data
  namespace: {{ .Values.module }}-{{ .Values.environment }}
  labels:
    {{- include "label-generator" . | nindent 4 }}
    module: {{ .Values.module }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistentVolume.storageClassName | default "local-path" }}
  resources:
    requests:
      storage: {{ .Values.persistentVolume.size | default "1Gi" }}