# kafka-cluster/values.yaml
kafka:
  version: 3.8.0
  replicas: 3
  replicationFactor: 3
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 5Gi
        class: local-path
zookeeper:
  replicas: 3
  storage:
    type: persistent-claim
    size: 5Gi
    class: local-path
